### ISSUE TITLE
Swapping the position of equal and backspace

### ISSUE THREAD

**Issue by avinash** [mikkosyrja/speedcrunch-android#3]
Hi,

I suggest that an option be added to swap the position of equal and backspace.

For me, equal should be lower right as on most calculators while backspace should be at the top like on most keyboards.

Thanks for considering.

**Comment by mikkosyrja** [comment]
I have toyed with idea of fully configurable keyboard. It will probably mean json files containing key definitions and setting list for selecting configuration file. Should not be too difficult, because SpeedCrunch is mostly text based system. Just read button definition from configuration file and put it into editing field. Special handling is needed with some editing buttons (enter, backspace, left arrow, right arrow), but that can be arranged. Stay tuned.

**Comment by avinash** [comment]
Hi,

Having a fully configurable keyboard is a great idea!!! Maybe having only the option to swap equal and backspace initially can be easier to implement?

**Comment by mikkosyrja** [comment]
Initial version of configurable keyboard is now available: https://bitbucket.org/heldercorreia/speedcrunch/pull-requests/107/user-configurable-keypad/diff
